# Generated by Django 5.2.1 on 2025-06-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SkillSwap_Network", "0010_rename_readrecipt_readreceipt_chatroom_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="readreceipt",
            name="message",
        ),
        migrations.AlterUniqueTogether(
            name="readreceipt",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="readreceipt",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="ReadReceipt",
        ),
    ]
